name: brick_breaker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.16.0
  flame_audio: ^2.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gamepads: ^0.1.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
  - family: イカモドキ
    fonts:
      - asset: assets/fonts/ikamodoki/ikamodoki1_0.ttf
        weight: 400
  assets:
    - assets/audio/
    - assets/images/
